version: 0.0
os: linux
files:
  - source: src/main/java/com/
    destination: /opt/tomcat/tomcat-10/webapps/boot/WEB-INF/classes/com/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  Afterinstall:
    - location: Scripts/deploy/deploy.sh
      timeout: 60
      runas: ubuntu
